project:
  type: website

website:
  title: "Shared Resources"
  sidebar:
    contents:
      - index.qmd
      - section: "Docs"
        contents:
          - docs/api.qmd
          - section: "Internals"
            contents:
              - docs/internals/architecture.qmd
