/**
 * @quarto/pandoc-types
 *
 * Pure type definitions for Pandoc JSON AST and quarto-markdown-pandoc extensions.
 * Zero runtime dependencies.
 */

export type {
  // Supporting types
  Attr,
  Target,
  MathType,
  QuoteType,
  ListNumberStyle,
  ListNumberDelim,
  ListAttributes,
  Citation,
  CitationMode,
  Alignment,
  ColWidth,
  ColSpec,
  Row,
  Cell,
  TableHead,
  TableBody,
  TableFoot,
  Caption,

  // Base Inline types
  Inline,
  Inline_Str,
  Inline_Space,
  Inline_SoftBreak,
  Inline_LineBreak,
  Inline_Emph,
  Inline_Strong,
  Inline_Strikeout,
  Inline_Superscript,
  Inline_Subscript,
  Inline_SmallCaps,
  Inline_Underline,
  Inline_Quoted,
  Inline_Code,
  Inline_Math,
  Inline_RawInline,
  Inline_Link,
  Inline_Image,
  Inline_Span,
  Inline_Cite,
  Inline_Note,

  // Base Block types
  Block,
  Block_Plain,
  Block_Para,
  Block_Header,
  Block_CodeBlock,
  Block_RawBlock,
  Block_BlockQuote,
  Block_BulletList,
  Block_OrderedList,
  Block_DefinitionList,
  Block_Div,
  Block_HorizontalRule,
  Block_Null,
  Block_Table,
  Block_Figure,

  // Base Meta types
  MetaValue,
  MetaValue_Map,
  MetaValue_List,
  MetaValue_Bool,
  MetaValue_String,
  MetaValue_Inlines,
  MetaValue_Blocks,

  // Base Document
  PandocDocument,

  // Source info types
  AttrSourceInfo,
  TargetSourceInfo,
  CellSourceInfo,
  RowSourceInfo,
  TableHeadSourceInfo,
  TableBodySourceInfo,
  TableFootSourceInfo,
  SerializableSourceInfo,
  SourceContext,
  SourceInfoErrorHandler,

  // Annotated Inline types
  Annotated_Inline,
  Annotated_Inline_Str,
  Annotated_Inline_Space,
  Annotated_Inline_SoftBreak,
  Annotated_Inline_LineBreak,
  Annotated_Inline_Emph,
  Annotated_Inline_Strong,
  Annotated_Inline_Strikeout,
  Annotated_Inline_Superscript,
  Annotated_Inline_Subscript,
  Annotated_Inline_SmallCaps,
  Annotated_Inline_Underline,
  Annotated_Inline_Quoted,
  Annotated_Inline_Code,
  Annotated_Inline_Math,
  Annotated_Inline_RawInline,
  Annotated_Inline_Link,
  Annotated_Inline_Image,
  Annotated_Inline_Span,
  Annotated_Inline_Cite,
  Annotated_Inline_Note,
  Annotated_Citation,

  // Annotated Block types
  Annotated_Block,
  Annotated_Block_Plain,
  Annotated_Block_Para,
  Annotated_Block_Header,
  Annotated_Block_CodeBlock,
  Annotated_Block_RawBlock,
  Annotated_Block_BlockQuote,
  Annotated_Block_BulletList,
  Annotated_Block_OrderedList,
  Annotated_Block_DefinitionList,
  Annotated_Block_Div,
  Annotated_Block_HorizontalRule,
  Annotated_Block_Null,
  Annotated_Block_Table,
  Annotated_Block_Figure,
  Annotated_Row,
  Annotated_Cell,
  Annotated_TableHead_Array,
  Annotated_TableBody_Array,
  Annotated_TableFoot_Array,
  Annotated_CaptionArray,
  Annotated_Caption,

  // Annotated Meta types
  Annotated_MetaValue,
  Annotated_MetaValue_Map,
  Annotated_MetaValue_List,
  Annotated_MetaValue_Bool,
  Annotated_MetaValue_String,
  Annotated_MetaValue_Inlines,
  Annotated_MetaValue_Blocks,

  // I/O types
  JSONValue,
  StructuralKind,
  JsonMetaValue,
  MetaMapEntry,
  RustFileInfo,
  RustQmdJson,
} from './types.js';

export {
  isInline,
  isBlock,
} from './types.js';
