project:
  type: website

website:
  title: "My Site"
  site-url: "https://example.com/my-site"
  favicon: favicon.svg
  sidebar:
    contents:
      - index.qmd
      - guides.qmd
      - api.qmd
  page-navigation: true

format:
  html:
    theme: cosmo
