/*
 * spec/mod.rs
 * Copyright (c) 2026 Posit, PBC
 */

//! The command specification quarto-math parses and writes against.
//!
//! `spec/commands.json` (q2-owned, generated by `cargo xtask gen-math-spec`
//! from mitex's spec dump plus `spec/overrides.json`) holds one row per
//! command or environment:
//!
//! ```json
//! "frac": { "parse": { "Cmd": { "args": …, "alias": null } },
//!           "sem":   { "kind": "frac", "style": "bar" },
//!           "typst": null }
//! ```
//!
//! `parse` is mitex's own `CommandSpecItem` (argument shapes), handed to the
//! vendored parser unchanged; `sem` is what the writers act on
//! ([`Semantics`]); `typst` is the Typst writer's alias, when mitex had one.

use std::collections::BTreeMap;
use std::sync::OnceLock;

use mitex_spec::{CommandSpec, CommandSpecItem};
use rustc_hash::FxHashMap;
use serde::{Deserialize, Serialize};

#[cfg(feature = "spec-gen")]
pub mod generator;
pub mod semantics;

pub use semantics::*;

/// The bundled `commands.json`.
const BUILTIN_JSON: &str = include_str!("../../spec/commands.json");

/// One row of `commands.json`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Row {
    /// mitex's argument shape for the parser.
    pub parse: CommandSpecItem,
    /// What the writers do with it.
    pub sem: Semantics,
    /// Typst alias, if mitex had one (`null` means "same name").
    #[serde(default)]
    pub typst: Option<String>,
}

/// The on-disk shape of `commands.json`: rows keyed by command or
/// environment name, sorted (a `BTreeMap`) so regeneration is byte-stable.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SpecFile {
    pub commands: BTreeMap<String, Row>,
}

/// A parsed command specification.
#[derive(Debug, Clone)]
pub struct Spec {
    command_spec: CommandSpec,
    rows: FxHashMap<String, Row>,
}

impl Spec {
    /// The specification bundled with the crate. Parsed once per process.
    pub fn builtin() -> &'static Spec {
        static BUILTIN: OnceLock<Spec> = OnceLock::new();
        BUILTIN.get_or_init(|| {
            Spec::from_json(BUILTIN_JSON).expect("the bundled commands.json is valid")
        })
    }

    /// Parse a specification from `commands.json` text.
    pub fn from_json(json: &str) -> Result<Spec, serde_json::Error> {
        let file: SpecFile = serde_json::from_str(json)?;
        Ok(Spec::from_file(file))
    }

    /// Build a specification from its file form.
    pub fn from_file(file: SpecFile) -> Spec {
        let mut parse_items = FxHashMap::default();
        let mut rows = FxHashMap::default();
        for (name, row) in file.commands {
            parse_items.insert(name.clone(), row.parse.clone());
            rows.insert(name, row);
        }
        Spec {
            command_spec: CommandSpec::new(parse_items),
            rows,
        }
    }

    /// The argument-shape half of the spec, as the mitex parser wants it.
    pub fn command_spec(&self) -> &CommandSpec {
        &self.command_spec
    }

    /// The row for a command (without the backslash) or environment name.
    pub fn row(&self, name: &str) -> Option<&Row> {
        self.rows.get(name)
    }

    /// The writer semantics for a command or environment name.
    pub fn semantics(&self, name: &str) -> Option<&Semantics> {
        self.rows.get(name).map(|r| &r.sem)
    }

    /// The Typst alias for a command or environment name.
    pub fn typst_alias(&self, name: &str) -> Option<&str> {
        self.rows.get(name).and_then(|r| r.typst.as_deref())
    }

    /// All rows, in an unspecified order.
    pub fn rows(&self) -> impl Iterator<Item = (&str, &Row)> {
        self.rows.iter().map(|(k, v)| (k.as_str(), v))
    }

    /// Number of commands and environments in the spec.
    pub fn len(&self) -> usize {
        self.rows.len()
    }

    /// Whether the spec has no entries.
    pub fn is_empty(&self) -> bool {
        self.rows.is_empty()
    }
}
