[package]
name = "quarto-brand"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Parse and resolve `_brand.yml` brand configuration for Quarto"

[dependencies]
serde = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]

[lints]
workspace = true
