// parity: keep in sync with external-sources/quarto-cli/src/config/constants.ts

/**
 * Keys that belong to the "execute" partition of a document's merged metadata.
 * Used to populate Format.execute when partitioning Q1-style metadata.
 */
export const kExecuteDefaultsKeys: readonly string[] = [
  "fig-width",
  "fig-height",
  "fig-format",
  "fig-dpi",
  "fig-asp",
  "mermaid-format",
  "df-print",
  "error",
  "eval",
  "engine",
  "cache",
  "freeze",
  "echo",
  "output",
  "warning",
  "include",
  "keep-md",
  "keep-ipynb",
  "enabled",
  "ipynb",
  "daemon",
  "daemon-restart",
  "debug",
  "ipynb-filter",
  "ipynb-filters",
  "ipynb-shell-interactivity",
  "plotly-connected",
];

/**
 * Keys that belong to the "render" partition of a document's merged metadata.
 * Used to populate Format.render when partitioning Q1-style metadata.
 */
export const kRenderDefaultsKeys: readonly string[] = [
  "keep-tex",
  "keep-typ",
  "keep-source",
  "keep-hidden",
  "remove-hidden",
  "clear-hidden-classes",
  "variant",
  "output-ext",
  "output-divs",
  "prefer-html",
  "page-width",
  "fig-align",
  "fig-pos",
  "fig-env",
  "code-fold",
  "code-link",
  "code-line-numbers",
  "code-overflow",
  "code-tools",
  "shortcodes",
  "tbl-colwidths",
  "inline-includes",
  "preserve-yaml",
  "merge-includes",
  "self-contained-math",
  "latex-auto-mk",
  "latex-auto-install",
  "latex-min-runs",
  "latex-max-runs",
  "latex-clean",
  "latex-input-paths",
  "latex-makeindex",
  "latex-makeindex-opts",
  "latex-tlmgr-opts",
  "latex-output-dir",
  "latex-tinytex",
  "pdf-standard",
  "link-external-icon",
  "link-external-newwindow",
  "link-external-filter",
  "format-resources",
  "format-links",
  "produce-source-notebook",
  "notebook-links",
  "notebook-subarticles",
  "notebook-view",
  "notebook-view-style",
  "notebook-preserve-cells",
  "clear-cell-options",
  "html-table-processing",
  "validate-yaml",
  "canonical-url",
  "body-classes",
];

/**
 * Keys that belong to the "pandoc" partition of a document's merged metadata.
 * Used to populate Format.pandoc when partitioning Q1-style metadata.
 */
export const kPandocDefaultsKeys: readonly string[] = [
  "to",
  "from",
  "reader",
  "writer",
  "output-file",
  "input-files",
  "defaults",
  "template",
  "standalone",
  "self-contained",
  "embed-resources",
  "variables",
  "metadata",
  "metadata-files",
  "metadata-file",
  "include-before-body",
  "include-after-body",
  "include-in-header",
  "resource-path",
  "citeproc",
  "cite-method",
  "citation-abbreviations",
  "filters",
  "file-scope",
  "data-dir",
  "verbosity",
  "log-file",
  "top-level-division",
  "abbreviations",
  "pdf-engine",
  "pdf-engine-opts",
  "pdf-engine-opt",
  "pdf-standard",
  "wrap",
  "columns",
  "dpi",
  "extract-media",
  "toc",
  "table-of-contents",
  "toc-depth",
  "number-sections",
  "number-offset",
  "shift-heading-level-by",
  "section-divs",
  "identifier-prefix",
  "title-prefix",
  "eol",
  "strip-comments",
  "indented-code-classes",
  "ascii",
  "default-image-extension",
  "highlight-style",
  "syntax-highlighting",
  "syntax-definitions",
  "syntax-definition",
  "listings",
  "reference-doc",
  "html-math-method",
  "email-obfuscation",
  "tab-stop",
  "preserve-tabs",
  "incremental",
  "slide-level",
  "epub-subdirectory",
  "epub-metadata",
  "epub-fonts",
  "epub-chapter-level",
  "epub-cover-image",
  "reference-links",
  "reference-location",
  "markdown-headings",
  "track-changes",
  "html-q-tags",
  "css",
  "ipynb-output",
  "request-headers",
  "fail-if-warnings",
  "dump-args",
  "ignore-args",
  "trace",
];

/**
 * Keys that belong to the "identifier" partition of a document's merged metadata.
 * Used to populate Format.identifier when partitioning Q1-style metadata.
 *
 * `base-format` is intentionally NOT listed (matches Q1's kIdentifierDefaultsKeys,
 * which is also these three). These lists route the flat `format.metadata` map; the
 * identifier arrives on the wire pre-structured as `format.identifier` (a nested
 * object the harness passes through verbatim), so `base-format` never needs routing.
 * Do NOT add it here on a Q1 re-sync — the parity test diffs three-against-three and
 * would stay green even if `base-format` were wrongly added to both sides.
 */
export const kIdentifierDefaultsKeys: readonly string[] = [
  "target-format",
  "display-name",
  "extension-name",
];

/**
 * Q1's "language" key set. NOTE: unlike the four lists above, this is **not**
 * consulted by the metadata partition. Q1's `metadataAsFormat`
 * (config/metadata.ts:200-210) classifies flat keys against only
 * kIdentifier/Render/Execute/PandocDefaultsKeys — it has no flat-key language
 * branch. `Format.language` is populated solely by the nested `language:` bin
 * peel, never by routing a flat key through this list. Kept here, transcribed
 * from Q1, for parity-completeness (the parity test diffs it against
 * constants.ts) and for any future consumer. See Plan 1b "Resolved partition
 * decisions" #1.
 */
export const kLanguageDefaultsKeys: readonly string[] = [
  "toc-title-document",
  "toc-title-website",
  "related-formats-title",
  "other-links-title",
  "code-links-title",
  "launch-dev-container-title",
  "launch-binder-title",
  "related-notebooks-title",
  "source-notebooks-prefix",
  "callout-tip-title",
  "callout-note-title",
  "callout-warning-title",
  "callout-important-title",
  "callout-caution-title",
  "callout-tip-prefix",
  "callout-note-prefix",
  "callout-warning-prefix",
  "callout-important-prefix",
  "callout-caution-prefix",
  "section-title-abstract",
  "section-title-footnotes",
  "section-title-references",
  "section-title-appendices",
  "section-title-reuse",
  "section-title-copyright",
  "section-title-citation",
  "appendix-attribution-bibtex",
  "appendix-attribution-cite-as",
  "appendix-view-license",
  "title-block-author-single",
  "title-block-published",
  "title-block-modified",
  "title-block-keywords",
  "code-summary",
  "code-line",
  "code-lines",
  "code-tools-menu-caption",
  "code-tools-show-all-code",
  "code-tools-hide-all-code",
  "code-tools-view-source",
  "code-tools-source-code",
  "tools-share",
  "tools-download",
  "search-no-results-text",
  "search-label",
  "toggle-dark-mode",
  "toggle-navigation",
  "toggle-reader-mode",
  "toggle-sidebar",
  "toggle-section",
  "copy-button-tooltip",
  "copy-button-tooltip-success",
  "back-to-top",
  "repo-action-links-edit",
  "repo-action-links-source",
  "repo-action-links-issue",
  "search-matching-documents-text",
  "search-copy-link-title",
  "search-hide-matches-text",
  "search-more-match-text",
  "search-more-matches-text",
  "search-clear-button-title",
  "search-text-placeholder",
  "search-detached-cancel-button-title",
  "search-submit-button-title",
  "crossref-fig-title",
  "crossref-tbl-title",
  "crossref-lst-title",
  "crossref-thm-title",
  "crossref-lem-title",
  "crossref-cor-title",
  "crossref-prp-title",
  "crossref-cnj-title",
  "crossref-def-title",
  "crossref-exm-title",
  "crossref-exr-title",
  "crossref-fig-prefix",
  "crossref-tbl-prefix",
  "crossref-lst-prefix",
  "crossref-ch-prefix",
  "crossref-apx-prefix",
  "crossref-sec-prefix",
  "crossref-eq-prefix",
  "crossref-thm-prefix",
  "crossref-lem-prefix",
  "crossref-cor-prefix",
  "crossref-prp-prefix",
  "crossref-cnj-prefix",
  "crossref-def-prefix",
  "crossref-exm-prefix",
  "crossref-exr-prefix",
  "crossref-lof-title",
  "crossref-lot-title",
  "crossref-lol-title",
  "environment-proof-title",
  "environment-remark-title",
  "environment-solution-title",
  "listing-page-filter",
  "listing-page-order-by",
  "listing-page-order-by-default",
  "listing-page-order-by-date-asc",
  "listing-page-order-by-date-desc",
  "listing-page-order-by-number-asc",
  "listing-page-order-by-number-desc",
  "listing-page-field-date",
  "listing-page-field-title",
  "listing-page-field-description",
  "listing-page-field-author",
  "listing-page-field-filename",
  "listing-page-field-filemodified",
  "listing-page-field-subtitle",
  "listing-page-field-readingtime",
  "listing-page-field-wordcount",
  "listing-page-field-categories",
  "listing-page-minutes-compact",
  "listing-page-words",
  "listing-page-category-all",
  "listing-page-no-matches",
  "title-block-author-single", // duplicated in Q1 source
  "title-block-author-plural",
  "title-block-affiliation-single",
  "title-block-affiliation-plural",
  "title-block-published", // duplicated in Q1 source
  "title-block-modified", // duplicated in Q1 source
  "title-block-keywords", // duplicated in Q1 source
  "notebook-preview-download",
  "notebook-preview-download-src",
  "notebook-preview-back",
  "article-notebook-label",
  "draft",
  "manuscript-meca-bundle",
];
