/*
 * toc_render.rs
 * Copyright (c) 2025 Posit, PBC
 *
 * Transform that renders TOC metadata to HTML.
 */

//! TOC rendering transform for HTML output.
//!
//! This transform reads the TOC structure from `navigation.toc` metadata
//! (generated by [`TocGenerateTransform`](super::TocGenerateTransform) or
//! provided by the user) and renders it to HTML, storing the result at
//! `rendered.navigation.toc`.
//!
//! ## Pipeline Position
//!
//! This transform should run after `TocGenerateTransform` (which creates
//! the `navigation.toc` structure) and before the template is applied.
//!
//! ## User Override
//!
//! Users can bypass this transform by providing their own pre-rendered
//! HTML at `rendered.navigation.toc` in the document metadata. The
//! transform detects this and skips rendering.
//!
//! ## HTML Output Structure
//!
//! The rendered HTML uses Bootstrap-compatible classes and attributes
//! for JavaScript scroll tracking:
//!
//! ```html
//! <ul>
//!   <li>
//!     <a href="#intro" class="nav-link" data-scroll-target="#intro">
//!       Introduction
//!     </a>
//!     <ul>
//!       <!-- nested entries -->
//!     </ul>
//!   </li>
//! </ul>
//! ```

use pampa::toc::{NavigationToc, TocEntry};
use quarto_pandoc_types::config_value::ConfigValue;
use quarto_pandoc_types::inline::{
    Cite, Delete, EditComment, Emph, Highlight, Inline, Inlines, Insert, Quoted, SmallCaps, Span,
    Strikeout, Strong, Subscript, Superscript, Underline,
};
use quarto_pandoc_types::pandoc::Pandoc;
use quarto_source_map::{By, SourceInfo};

use crate::Result;
use crate::render::RenderContext;
use crate::transform::{AstTransform, TransformPhase};
use crate::transforms::is_feature_disabled;

/// Transform that renders TOC to HTML.
///
/// This transform is format-specific (HTML). It reads the TOC structure
/// from metadata and renders it to HTML for template insertion.
pub struct TocRenderTransform;

impl TocRenderTransform {
    /// Create a new TOC render transform.
    pub fn new() -> Self {
        Self
    }
}

impl Default for TocRenderTransform {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait::async_trait(?Send)]
impl AstTransform for TocRenderTransform {
    fn name(&self) -> &str {
        "toc-render"
    }

    fn phase(&self) -> TransformPhase {
        TransformPhase::Navigation
    }

    async fn transform(&self, ast: &mut Pandoc, _ctx: &mut RenderContext) -> Result<()> {
        // Affirmative disable: `toc: false` in merged metadata suppresses
        // rendering even if `navigation.toc` has been pre-populated.
        if is_feature_disabled(&ast.meta, "toc") {
            return Ok(());
        }

        // Skip if already rendered (user provided pre-rendered HTML)
        if ast.meta.contains_path(&["rendered", "navigation", "toc"]) {
            return Ok(());
        }

        // Skip if no TOC data to render
        let Some(toc_data) = ast.meta.get_path(&["navigation", "toc"]) else {
            return Ok(());
        };

        // Parse the TOC structure
        let Some(toc) = NavigationToc::from_config_value(toc_data) else {
            return Ok(());
        };

        // Skip if no entries
        if toc.entries.is_empty() {
            return Ok(());
        }

        // Render to HTML
        let html = render_toc_entries_to_html(&toc.entries);

        // Store rendered HTML
        ast.meta.insert_path(
            &["rendered", "navigation", "toc"],
            ConfigValue::new_string(&html, SourceInfo::generated(By::programmatic_config())),
        );

        Ok(())
    }
}

/// Strip the inlines a TOC entry label cannot carry, mirroring Pandoc's
/// `deLink` / `deNote`.
///
/// Two kinds have to go:
///
/// - **`Link`** — the entry *is* an `<a>`, and anchors may not nest.
///   Pandoc unwraps the link to its content, so the link's text still
///   reads in the TOC; Quarto 1 does the same (`## … and a [link](…)`
///   yields `… and a link`).
/// - **`Note` / `NoteReference`** — a footnote marker in a TOC entry is
///   noise, and rendering the note body there would duplicate it.
///
/// Everything else renders. This filtering deliberately lives at *render*
/// time rather than in `generate_toc`: `TocEntry` is also
/// `DocumentProfile::outline`, a faithful semantic outline, and "an
/// anchor may not nest" is a constraint of this HTML output, not a fact
/// about the document's headings.
///
/// The match is exhaustive on purpose — a new `Inline` variant should
/// force a decision here rather than silently fall through a `_` arm,
/// which is how the flattener this replaced accumulated its bugs.
fn strip_links_and_notes(inlines: &[Inline]) -> Inlines {
    let mut out = Inlines::new();
    for inline in inlines {
        match inline {
            // Unwrap: keep the text, drop the anchor.
            Inline::Link(l) => out.extend(strip_links_and_notes(&l.content)),

            // Drop entirely.
            Inline::Note(_) | Inline::NoteReference(_) => {}

            // Recurse into containers, preserving the wrapper.
            Inline::Emph(e) => out.push(Inline::Emph(Emph {
                content: strip_links_and_notes(&e.content),
                ..e.clone()
            })),
            Inline::Underline(u) => out.push(Inline::Underline(Underline {
                content: strip_links_and_notes(&u.content),
                ..u.clone()
            })),
            Inline::Strong(s) => out.push(Inline::Strong(Strong {
                content: strip_links_and_notes(&s.content),
                ..s.clone()
            })),
            Inline::Strikeout(s) => out.push(Inline::Strikeout(Strikeout {
                content: strip_links_and_notes(&s.content),
                ..s.clone()
            })),
            Inline::Superscript(s) => out.push(Inline::Superscript(Superscript {
                content: strip_links_and_notes(&s.content),
                ..s.clone()
            })),
            Inline::Subscript(s) => out.push(Inline::Subscript(Subscript {
                content: strip_links_and_notes(&s.content),
                ..s.clone()
            })),
            Inline::SmallCaps(s) => out.push(Inline::SmallCaps(SmallCaps {
                content: strip_links_and_notes(&s.content),
                ..s.clone()
            })),
            Inline::Quoted(q) => out.push(Inline::Quoted(Quoted {
                content: strip_links_and_notes(&q.content),
                ..q.clone()
            })),
            Inline::Cite(c) => out.push(Inline::Cite(Cite {
                content: strip_links_and_notes(&c.content),
                ..c.clone()
            })),
            Inline::Span(s) => out.push(Inline::Span(Span {
                content: strip_links_and_notes(&s.content),
                ..s.clone()
            })),
            Inline::Insert(i) => out.push(Inline::Insert(Insert {
                content: strip_links_and_notes(&i.content),
                ..i.clone()
            })),
            Inline::Delete(d) => out.push(Inline::Delete(Delete {
                content: strip_links_and_notes(&d.content),
                ..d.clone()
            })),
            Inline::Highlight(h) => out.push(Inline::Highlight(Highlight {
                content: strip_links_and_notes(&h.content),
                ..h.clone()
            })),
            Inline::EditComment(e) => out.push(Inline::EditComment(EditComment {
                content: strip_links_and_notes(&e.content),
                ..e.clone()
            })),
            // An Image's `content` is alt text, not rendered children —
            // leave the node intact so the writer emits the `<img>`.
            Inline::Image(_)
            // Leaves.
            | Inline::Str(_)
            | Inline::Space(_)
            | Inline::SoftBreak(_)
            | Inline::LineBreak(_)
            | Inline::Code(_)
            | Inline::Math(_)
            | Inline::RawInline(_)
            | Inline::Shortcode(_)
            | Inline::Attr(_)
            | Inline::Custom(_) => out.push(inline.clone()),
        }
    }
    out
}

/// Render a TOC entry label to HTML through the real inline writer, so a
/// label matches the heading it points at (bd-toc-smart-quotes-6nro57ed).
///
/// This is the same `write_inlines_to` quarto-core already uses to render
/// inline metadata (`template.rs`, `revealjs/footer_logo.rs`); it handles
/// escaping, so the label no longer goes through `html_escape`.
fn render_toc_label(title: &[Inline]) -> String {
    let stripped = strip_links_and_notes(title);
    let mut out: Vec<u8> = Vec::new();
    match pampa::writers::html::write_inlines_to(&stripped, &mut out) {
        // Writing to a Vec cannot fail; the lossy conversion is for the
        // impossible case rather than an expected one.
        Ok(()) => String::from_utf8_lossy(&out).into_owned(),
        Err(_) => String::new(),
    }
}

/// Render TOC entries to HTML string (recursive).
fn render_toc_entries_to_html(entries: &[TocEntry]) -> String {
    if entries.is_empty() {
        return String::new();
    }

    let mut html = String::from("<ul>\n");
    for entry in entries {
        html.push_str("<li>\n");
        html.push_str(&format!(
            "<a href=\"#{}\" class=\"nav-link\" data-scroll-target=\"#{}\">\n",
            html_escape(&entry.id),
            html_escape(&entry.id)
        ));
        if let Some(ref number) = entry.number {
            html.push_str(&format!(
                "<span class=\"toc-number\">{}</span> ",
                html_escape(number)
            ));
        }
        html.push_str(&render_toc_label(&entry.title));
        html.push_str("\n</a>\n");

        if !entry.children.is_empty() {
            // Recursive call for nested entries
            html.push_str(&render_toc_entries_to_html(&entry.children));
        }
        html.push_str("</li>\n");
    }
    html.push_str("</ul>\n");
    html
}

/// Escape HTML special characters.
fn html_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#x27;")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::format::Format;
    use crate::project::{DocumentInfo, ProjectConfig, ProjectContext};
    use crate::render::BinaryDependencies;
    use quarto_pandoc_types::config_value::ConfigValue;
    use std::path::PathBuf;

    fn dummy_source_info() -> SourceInfo {
        SourceInfo::for_test()
    }

    fn make_test_project() -> ProjectContext {
        ProjectContext {
            dir: PathBuf::from("/project"),
            config: ProjectConfig::default(),
            is_single_file: true,
            files: vec![DocumentInfo::from_path("/project/doc.qmd")],
            output_dir: PathBuf::from("/project"),
        }
    }

    /// A title made of one literal `Str`. Tests that care about markup
    /// build their own inlines.
    fn plain_title(text: &str) -> Inlines {
        vec![Inline::Str(quarto_pandoc_types::inline::Str {
            text: text.to_string(),
            source_info: dummy_source_info(),
        })]
    }

    fn make_toc_entry(id: &str, title: &str, level: i32) -> TocEntry {
        TocEntry {
            id: id.to_string(),
            title: plain_title(title),
            level,
            number: None,
            children: vec![],
        }
    }

    #[tokio::test]
    async fn test_transform_name() {
        let transform = TocRenderTransform::new();
        assert_eq!(transform.name(), "toc-render");
    }

    #[tokio::test]
    async fn test_skips_when_no_toc_data() {
        let mut ast = Pandoc {
            meta: ConfigValue::default(),
            blocks: vec![],
        };

        let project = make_test_project();
        let doc = DocumentInfo::from_path("/project/doc.qmd");
        let format = Format::html();
        let binaries = BinaryDependencies::new();
        let mut ctx = RenderContext::new(&project, &doc, &format, &binaries);

        let transform = TocRenderTransform::new();
        transform.transform(&mut ast, &mut ctx).await.unwrap();

        // No rendered.navigation.toc should exist
        assert!(!ast.meta.contains_path(&["rendered", "navigation", "toc"]));
    }

    #[tokio::test]
    async fn test_skips_when_already_rendered() {
        let mut ast = Pandoc {
            meta: ConfigValue::default(),
            blocks: vec![],
        };

        // Pre-populate with user-provided rendered HTML
        ast.meta.insert_path(
            &["rendered", "navigation", "toc"],
            ConfigValue::new_string("<ul><li>Custom</li></ul>", dummy_source_info()),
        );

        // Also add navigation.toc (would normally trigger rendering)
        let toc = NavigationToc {
            title: None,
            entries: vec![make_toc_entry("intro", "Introduction", 1)],
        };
        ast.meta
            .insert_path(&["navigation", "toc"], toc.to_config_value());

        let project = make_test_project();
        let doc = DocumentInfo::from_path("/project/doc.qmd");
        let format = Format::html();
        let binaries = BinaryDependencies::new();
        let mut ctx = RenderContext::new(&project, &doc, &format, &binaries);

        let transform = TocRenderTransform::new();
        transform.transform(&mut ast, &mut ctx).await.unwrap();

        // Should keep user-provided HTML
        let rendered = ast
            .meta
            .get_path(&["rendered", "navigation", "toc"])
            .unwrap();
        assert_eq!(rendered.as_str(), Some("<ul><li>Custom</li></ul>"));
    }

    #[tokio::test]
    async fn test_renders_simple_toc() {
        let mut ast = Pandoc {
            meta: ConfigValue::default(),
            blocks: vec![],
        };

        let toc = NavigationToc {
            title: Some("Contents".to_string()),
            entries: vec![
                make_toc_entry("intro", "Introduction", 1),
                make_toc_entry("methods", "Methods", 1),
            ],
        };
        ast.meta
            .insert_path(&["navigation", "toc"], toc.to_config_value());

        let project = make_test_project();
        let doc = DocumentInfo::from_path("/project/doc.qmd");
        let format = Format::html();
        let binaries = BinaryDependencies::new();
        let mut ctx = RenderContext::new(&project, &doc, &format, &binaries);

        let transform = TocRenderTransform::new();
        transform.transform(&mut ast, &mut ctx).await.unwrap();

        // Should have rendered.navigation.toc
        assert!(ast.meta.contains_path(&["rendered", "navigation", "toc"]));

        let rendered = ast
            .meta
            .get_path(&["rendered", "navigation", "toc"])
            .unwrap();
        let html = rendered.as_str().unwrap();

        // Check structure
        assert!(html.contains("<ul>"));
        assert!(html.contains("</ul>"));
        assert!(html.contains("<li>"));
        assert!(html.contains("</li>"));
        assert!(html.contains("href=\"#intro\""));
        assert!(html.contains("href=\"#methods\""));
        assert!(html.contains("Introduction"));
        assert!(html.contains("Methods"));
        assert!(html.contains("class=\"nav-link\""));
        assert!(html.contains("data-scroll-target=\"#intro\""));
    }

    #[tokio::test]
    async fn test_renders_nested_toc() {
        let mut ast = Pandoc {
            meta: ConfigValue::default(),
            blocks: vec![],
        };

        let toc = NavigationToc {
            title: None,
            entries: vec![TocEntry {
                id: "chapter".to_string(),
                title: plain_title("Chapter 1"),
                level: 1,
                number: None,
                children: vec![
                    make_toc_entry("section-a", "Section A", 2),
                    make_toc_entry("section-b", "Section B", 2),
                ],
            }],
        };
        ast.meta
            .insert_path(&["navigation", "toc"], toc.to_config_value());

        let project = make_test_project();
        let doc = DocumentInfo::from_path("/project/doc.qmd");
        let format = Format::html();
        let binaries = BinaryDependencies::new();
        let mut ctx = RenderContext::new(&project, &doc, &format, &binaries);

        let transform = TocRenderTransform::new();
        transform.transform(&mut ast, &mut ctx).await.unwrap();

        let rendered = ast
            .meta
            .get_path(&["rendered", "navigation", "toc"])
            .unwrap();
        let html = rendered.as_str().unwrap();

        // Check nested structure - there should be nested <ul> tags
        // Count occurrences of <ul>
        let ul_count = html.matches("<ul>").count();
        assert!(ul_count >= 2, "Should have nested <ul> tags");

        // Check all entries are present
        assert!(html.contains("Chapter 1"));
        assert!(html.contains("Section A"));
        assert!(html.contains("Section B"));
    }

    #[tokio::test]
    async fn test_renders_toc_with_numbers() {
        let mut ast = Pandoc {
            meta: ConfigValue::default(),
            blocks: vec![],
        };

        let toc = NavigationToc {
            title: None,
            entries: vec![TocEntry {
                id: "intro".to_string(),
                title: plain_title("Introduction"),
                level: 1,
                number: Some("1".to_string()),
                children: vec![TocEntry {
                    id: "background".to_string(),
                    title: plain_title("Background"),
                    level: 2,
                    number: Some("1.1".to_string()),
                    children: vec![],
                }],
            }],
        };
        ast.meta
            .insert_path(&["navigation", "toc"], toc.to_config_value());

        let project = make_test_project();
        let doc = DocumentInfo::from_path("/project/doc.qmd");
        let format = Format::html();
        let binaries = BinaryDependencies::new();
        let mut ctx = RenderContext::new(&project, &doc, &format, &binaries);

        let transform = TocRenderTransform::new();
        transform.transform(&mut ast, &mut ctx).await.unwrap();

        let rendered = ast
            .meta
            .get_path(&["rendered", "navigation", "toc"])
            .unwrap();
        let html = rendered.as_str().unwrap();

        // Check section numbers are rendered
        assert!(html.contains("<span class=\"toc-number\">1</span>"));
        assert!(html.contains("<span class=\"toc-number\">1.1</span>"));
    }

    #[tokio::test]
    async fn test_html_escape() {
        // Test that special characters are escaped
        assert_eq!(html_escape("a & b"), "a &amp; b");
        assert_eq!(html_escape("<script>"), "&lt;script&gt;");
        assert_eq!(html_escape("\"quoted\""), "&quot;quoted&quot;");
        assert_eq!(html_escape("it's"), "it&#x27;s");
    }

    #[tokio::test]
    async fn test_renders_toc_escapes_special_chars() {
        // The label no longer goes through `html_escape` — escaping now
        // happens inside the inline writer. The distinction that matters
        // after that change: characters *typed* in a heading arrive as
        // `Str` content and must still be escaped, so a literal `<b>`
        // renders as text rather than opening a tag. (A `RawInline`
        // would legitimately pass through; that is a different node and
        // is not what a plain heading produces.)
        //
        // The entry `id` still goes through `html_escape` — it is an
        // attribute value, not inline content.
        let mut ast = Pandoc {
            meta: ConfigValue::default(),
            blocks: vec![],
        };

        let toc = NavigationToc {
            title: None,
            entries: vec![TocEntry {
                id: "intro-with-<script>".to_string(),
                title: plain_title("Title with <b>HTML</b> & \"quotes\""),
                level: 1,
                number: None,
                children: vec![],
            }],
        };
        ast.meta
            .insert_path(&["navigation", "toc"], toc.to_config_value());

        let project = make_test_project();
        let doc = DocumentInfo::from_path("/project/doc.qmd");
        let format = Format::html();
        let binaries = BinaryDependencies::new();
        let mut ctx = RenderContext::new(&project, &doc, &format, &binaries);

        let transform = TocRenderTransform::new();
        transform.transform(&mut ast, &mut ctx).await.unwrap();

        let rendered = ast
            .meta
            .get_path(&["rendered", "navigation", "toc"])
            .unwrap();
        let html = rendered.as_str().unwrap();

        assert!(
            html.contains("&lt;b&gt;HTML&lt;/b&gt;"),
            "literal angle brackets in heading text must be escaped; got: {html}"
        );
        assert!(html.contains("&amp;"), "literal ampersand must be escaped");
        assert!(
            html.contains("intro-with-&lt;script&gt;"),
            "the entry id is an attribute value and stays html_escape'd"
        );
    }

    /// bd-toc-smart-quotes-6nro57ed: the label carries the heading's
    /// markup rather than a flattened projection.
    #[tokio::test]
    async fn test_renders_toc_label_with_markup() {
        use quarto_pandoc_types::inline::{Code, QuoteType, Quoted, Str};

        let title = vec![
            Inline::Str(Str {
                text: "Using a ".to_string(),
                source_info: dummy_source_info(),
            }),
            Inline::Quoted(Quoted {
                quote_type: QuoteType::DoubleQuote,
                content: vec![Inline::Str(Str {
                    text: "raw".to_string(),
                    source_info: dummy_source_info(),
                })],
                source_info: dummy_source_info(),
            }),
            Inline::Str(Str {
                text: " ".to_string(),
                source_info: dummy_source_info(),
            }),
            Inline::Code(Code {
                text: "volume".to_string(),
                attr: (String::new(), vec![], hashlink::LinkedHashMap::new()),
                source_info: dummy_source_info(),
                attr_source: quarto_pandoc_types::attr::AttrSourceInfo::empty(),
            }),
        ];

        let html = render_toc_label(&title);

        assert_eq!(
            html, "Using a \u{201C}raw\u{201D} <code>volume</code>",
            "quote delimiters and the code span must both render"
        );
    }

    /// Links are unwrapped (anchors may not nest) and notes dropped,
    /// mirroring pandoc's `deLink` / `deNote`.
    #[tokio::test]
    async fn test_toc_label_strips_links_and_notes() {
        use quarto_pandoc_types::inline::{Link, Note, Str};

        let title = vec![
            Inline::Str(Str {
                text: "See ".to_string(),
                source_info: dummy_source_info(),
            }),
            Inline::Link(Link {
                attr: (String::new(), vec![], hashlink::LinkedHashMap::new()),
                content: vec![Inline::Str(Str {
                    text: "the docs".to_string(),
                    source_info: dummy_source_info(),
                })],
                target: ("https://example.com".to_string(), String::new()),
                source_info: dummy_source_info(),
                attr_source: quarto_pandoc_types::attr::AttrSourceInfo::empty(),
                target_source: quarto_pandoc_types::attr::TargetSourceInfo::empty(),
            }),
            Inline::Note(Note {
                content: vec![],
                source_info: dummy_source_info(),
            }),
        ];

        let html = render_toc_label(&title);

        assert_eq!(html, "See the docs", "link text kept, anchor and note gone");
        assert!(
            !html.contains("<a"),
            "a nested anchor would be invalid inside the TOC entry's own <a>"
        );
    }

    #[tokio::test]
    async fn test_skips_when_toc_is_false() {
        // Even if navigation.toc is pre-populated (e.g. by a user setting it
        // directly in frontmatter, or from an earlier pipeline layer), a
        // top-level `toc: false` must suppress rendering. This is the
        // "affirmative disable" semantics shared across toc, navbar, and
        // page-footer.
        let mut ast = Pandoc {
            meta: ConfigValue::default(),
            blocks: vec![],
        };

        // Pre-populate navigation.toc (would normally render a TOC).
        let toc = NavigationToc {
            title: None,
            entries: vec![make_toc_entry("intro", "Introduction", 1)],
        };
        ast.meta
            .insert_path(&["navigation", "toc"], toc.to_config_value());

        // And set toc: false at top level.
        ast.meta.insert_path(
            &["toc"],
            ConfigValue::new_scalar(yaml_rust2::Yaml::Boolean(false), dummy_source_info()),
        );

        let project = make_test_project();
        let doc = DocumentInfo::from_path("/project/doc.qmd");
        let format = Format::html();
        let binaries = BinaryDependencies::new();
        let mut ctx = RenderContext::new(&project, &doc, &format, &binaries);

        let transform = TocRenderTransform::new();
        transform.transform(&mut ast, &mut ctx).await.unwrap();

        // Affirmative disable wins: no rendered.navigation.toc.
        assert!(
            !ast.meta.contains_path(&["rendered", "navigation", "toc"]),
            "`toc: false` must suppress rendering even when navigation.toc is pre-populated"
        );
    }

    #[tokio::test]
    async fn test_skips_empty_entries() {
        let mut ast = Pandoc {
            meta: ConfigValue::default(),
            blocks: vec![],
        };

        let toc = NavigationToc {
            title: Some("Contents".to_string()),
            entries: vec![], // Empty entries
        };
        ast.meta
            .insert_path(&["navigation", "toc"], toc.to_config_value());

        let project = make_test_project();
        let doc = DocumentInfo::from_path("/project/doc.qmd");
        let format = Format::html();
        let binaries = BinaryDependencies::new();
        let mut ctx = RenderContext::new(&project, &doc, &format, &binaries);

        let transform = TocRenderTransform::new();
        transform.transform(&mut ast, &mut ctx).await.unwrap();

        // Should not have rendered.navigation.toc (empty entries)
        assert!(!ast.meta.contains_path(&["rendered", "navigation", "toc"]));
    }

    #[tokio::test]
    async fn test_default_trait() {
        let _transform: TocRenderTransform = Default::default();
    }

    // === Tests for user-provided metadata in YAML-parsed format ===
    //
    // These tests verify that TOC metadata provided by users in document
    // frontmatter is correctly parsed, even when YAML parsing converts
    // values to PandocInlines or string-encoded integers.

    use quarto_pandoc_types::config_value::ConfigMapEntry;
    use quarto_pandoc_types::inline::{Inline, Space, Str};

    /// Create a ConfigValue containing PandocInlines with a single Str.
    /// This simulates how YAML strings are parsed in document frontmatter.
    fn yaml_string_value(s: &str) -> ConfigValue {
        ConfigValue::new_inlines(
            vec![Inline::Str(Str {
                text: s.to_string(),
                source_info: SourceInfo::for_test(),
            })],
            SourceInfo::for_test(),
        )
    }

    /// Create a ConfigValue containing PandocInlines with multiple words.
    /// This simulates YAML strings with spaces like "The Details".
    fn yaml_multiword_string(words: &[&str]) -> ConfigValue {
        let mut inlines = Vec::new();
        for (i, word) in words.iter().enumerate() {
            if i > 0 {
                inlines.push(Inline::Space(Space {
                    source_info: SourceInfo::for_test(),
                }));
            }
            inlines.push(Inline::Str(Str {
                text: word.to_string(),
                source_info: SourceInfo::for_test(),
            }));
        }
        ConfigValue::new_inlines(inlines, SourceInfo::for_test())
    }

    /// Create a ConfigValue for a string-encoded integer.
    /// This simulates how YAML integers are sometimes parsed as strings.
    fn yaml_int_as_string(n: i32) -> ConfigValue {
        ConfigValue::new_string(n.to_string(), SourceInfo::for_test())
    }

    /// Create a TOC entry ConfigValue in YAML-parsed format.
    fn yaml_toc_entry(id: &str, title: &str, level: i32) -> ConfigValue {
        ConfigValue::new_map(
            vec![
                ConfigMapEntry {
                    key: "id".to_string(),
                    key_source: SourceInfo::for_test(),
                    value: yaml_string_value(id),
                },
                ConfigMapEntry {
                    key: "title".to_string(),
                    key_source: SourceInfo::for_test(),
                    value: yaml_string_value(title),
                },
                ConfigMapEntry {
                    key: "level".to_string(),
                    key_source: SourceInfo::for_test(),
                    value: yaml_int_as_string(level),
                },
            ],
            SourceInfo::for_test(),
        )
    }

    /// Create a TOC entry with multiword title in YAML-parsed format.
    fn yaml_toc_entry_multiword(id: &str, title_words: &[&str], level: i32) -> ConfigValue {
        ConfigValue::new_map(
            vec![
                ConfigMapEntry {
                    key: "id".to_string(),
                    key_source: SourceInfo::for_test(),
                    value: yaml_string_value(id),
                },
                ConfigMapEntry {
                    key: "title".to_string(),
                    key_source: SourceInfo::for_test(),
                    value: yaml_multiword_string(title_words),
                },
                ConfigMapEntry {
                    key: "level".to_string(),
                    key_source: SourceInfo::for_test(),
                    value: yaml_int_as_string(level),
                },
            ],
            SourceInfo::for_test(),
        )
    }

    /// Create a TOC entry with children in YAML-parsed format.
    fn yaml_toc_entry_with_children(
        id: &str,
        title_words: &[&str],
        level: i32,
        children: Vec<ConfigValue>,
    ) -> ConfigValue {
        ConfigValue::new_map(
            vec![
                ConfigMapEntry {
                    key: "id".to_string(),
                    key_source: SourceInfo::for_test(),
                    value: yaml_string_value(id),
                },
                ConfigMapEntry {
                    key: "title".to_string(),
                    key_source: SourceInfo::for_test(),
                    value: yaml_multiword_string(title_words),
                },
                ConfigMapEntry {
                    key: "level".to_string(),
                    key_source: SourceInfo::for_test(),
                    value: yaml_int_as_string(level),
                },
                ConfigMapEntry {
                    key: "children".to_string(),
                    key_source: SourceInfo::for_test(),
                    value: ConfigValue::new_array(children, SourceInfo::for_test()),
                },
            ],
            SourceInfo::for_test(),
        )
    }

    #[tokio::test]
    async fn test_renders_yaml_parsed_toc_simple() {
        // Simulates user-provided YAML:
        // navigation:
        //   toc:
        //     entries:
        //       - id: "tldr"
        //         title: "TL;DR"
        //         level: 1
        let mut ast = Pandoc {
            meta: ConfigValue::default(),
            blocks: vec![],
        };

        let toc_value = ConfigValue::new_map(
            vec![ConfigMapEntry {
                key: "entries".to_string(),
                key_source: SourceInfo::for_test(),
                value: ConfigValue::new_array(
                    vec![yaml_toc_entry("tldr", "TL;DR", 1)],
                    SourceInfo::for_test(),
                ),
            }],
            SourceInfo::for_test(),
        );
        ast.meta.insert_path(&["navigation", "toc"], toc_value);

        let project = make_test_project();
        let doc = DocumentInfo::from_path("/project/doc.qmd");
        let format = Format::html();
        let binaries = BinaryDependencies::new();
        let mut ctx = RenderContext::new(&project, &doc, &format, &binaries);

        let transform = TocRenderTransform::new();
        transform.transform(&mut ast, &mut ctx).await.unwrap();

        // Should have rendered TOC
        assert!(ast.meta.contains_path(&["rendered", "navigation", "toc"]));

        let rendered = ast
            .meta
            .get_path(&["rendered", "navigation", "toc"])
            .unwrap();
        let html = rendered.as_str().unwrap();

        assert!(html.contains("href=\"#tldr\""));
        assert!(html.contains("TL;DR"));
        assert!(html.contains("data-scroll-target=\"#tldr\""));
    }

    #[tokio::test]
    async fn test_renders_yaml_parsed_toc_with_multiword_titles() {
        // Simulates user-provided YAML with multi-word titles:
        // navigation:
        //   toc:
        //     entries:
        //       - id: "details"
        //         title: "The Details"
        //         level: 1
        let mut ast = Pandoc {
            meta: ConfigValue::default(),
            blocks: vec![],
        };

        let toc_value = ConfigValue::new_map(
            vec![ConfigMapEntry {
                key: "entries".to_string(),
                key_source: SourceInfo::for_test(),
                value: ConfigValue::new_array(
                    vec![yaml_toc_entry_multiword("details", &["The", "Details"], 1)],
                    SourceInfo::for_test(),
                ),
            }],
            SourceInfo::for_test(),
        );
        ast.meta.insert_path(&["navigation", "toc"], toc_value);

        let project = make_test_project();
        let doc = DocumentInfo::from_path("/project/doc.qmd");
        let format = Format::html();
        let binaries = BinaryDependencies::new();
        let mut ctx = RenderContext::new(&project, &doc, &format, &binaries);

        let transform = TocRenderTransform::new();
        transform.transform(&mut ast, &mut ctx).await.unwrap();

        let rendered = ast
            .meta
            .get_path(&["rendered", "navigation", "toc"])
            .unwrap();
        let html = rendered.as_str().unwrap();

        assert!(html.contains("href=\"#details\""));
        assert!(html.contains("The Details"));
    }

    #[tokio::test]
    async fn test_renders_yaml_parsed_toc_with_nested_children() {
        // Simulates user-provided YAML with nested structure:
        // navigation:
        //   toc:
        //     entries:
        //       - id: "details"
        //         title: "The Details"
        //         level: 1
        //         children:
        //           - id: "part-a"
        //             title: "Part A"
        //             level: 2
        let mut ast = Pandoc {
            meta: ConfigValue::default(),
            blocks: vec![],
        };

        let child_entry = yaml_toc_entry_multiword("part-a", &["Part", "A"], 2);
        let parent_entry =
            yaml_toc_entry_with_children("details", &["The", "Details"], 1, vec![child_entry]);

        let toc_value = ConfigValue::new_map(
            vec![ConfigMapEntry {
                key: "entries".to_string(),
                key_source: SourceInfo::for_test(),
                value: ConfigValue::new_array(vec![parent_entry], SourceInfo::for_test()),
            }],
            SourceInfo::for_test(),
        );
        ast.meta.insert_path(&["navigation", "toc"], toc_value);

        let project = make_test_project();
        let doc = DocumentInfo::from_path("/project/doc.qmd");
        let format = Format::html();
        let binaries = BinaryDependencies::new();
        let mut ctx = RenderContext::new(&project, &doc, &format, &binaries);

        let transform = TocRenderTransform::new();
        transform.transform(&mut ast, &mut ctx).await.unwrap();

        let rendered = ast
            .meta
            .get_path(&["rendered", "navigation", "toc"])
            .unwrap();
        let html = rendered.as_str().unwrap();

        // Check parent entry
        assert!(html.contains("href=\"#details\""));
        assert!(html.contains("The Details"));

        // Check child entry
        assert!(html.contains("href=\"#part-a\""));
        assert!(html.contains("Part A"));

        // Verify nested structure (two ul elements)
        let ul_count = html.matches("<ul>").count();
        assert!(
            ul_count >= 2,
            "Expected nested <ul> tags, found {}",
            ul_count
        );
    }

    #[tokio::test]
    async fn test_user_provided_rendered_toc_used_directly() {
        // Simulates user providing pre-rendered HTML:
        // rendered:
        //   navigation:
        //     toc: "<ul><li>My Custom TOC</li></ul>"
        let mut ast = Pandoc {
            meta: ConfigValue::default(),
            blocks: vec![],
        };

        let custom_html = "<ul><li><a href=\"#custom\">My Custom TOC</a></li></ul>";
        ast.meta.insert_path(
            &["rendered", "navigation", "toc"],
            ConfigValue::new_string(custom_html, SourceInfo::for_test()),
        );

        // Also add navigation.toc that would normally be rendered
        let toc_value = ConfigValue::new_map(
            vec![ConfigMapEntry {
                key: "entries".to_string(),
                key_source: SourceInfo::for_test(),
                value: ConfigValue::new_array(
                    vec![yaml_toc_entry("intro", "Introduction", 1)],
                    SourceInfo::for_test(),
                ),
            }],
            SourceInfo::for_test(),
        );
        ast.meta.insert_path(&["navigation", "toc"], toc_value);

        let project = make_test_project();
        let doc = DocumentInfo::from_path("/project/doc.qmd");
        let format = Format::html();
        let binaries = BinaryDependencies::new();
        let mut ctx = RenderContext::new(&project, &doc, &format, &binaries);

        let transform = TocRenderTransform::new();
        transform.transform(&mut ast, &mut ctx).await.unwrap();

        // Should use user-provided HTML, not render from navigation.toc
        let rendered = ast
            .meta
            .get_path(&["rendered", "navigation", "toc"])
            .unwrap();
        assert_eq!(rendered.as_str(), Some(custom_html));

        // Verify it contains user content, not auto-rendered content
        let html = rendered.as_str().unwrap();
        assert!(html.contains("My Custom TOC"));
        assert!(!html.contains("Introduction")); // The navigation.toc entry should NOT appear
    }

    #[tokio::test]
    async fn test_yaml_parsed_toc_with_title() {
        // Simulates user-provided YAML with TOC title:
        // navigation:
        //   toc:
        //     title: "Quick Links"
        //     entries:
        //       - id: "intro"
        //         title: "Introduction"
        //         level: 1
        let mut ast = Pandoc {
            meta: ConfigValue::default(),
            blocks: vec![],
        };

        let toc_value = ConfigValue::new_map(
            vec![
                ConfigMapEntry {
                    key: "title".to_string(),
                    key_source: SourceInfo::for_test(),
                    value: yaml_multiword_string(&["Quick", "Links"]),
                },
                ConfigMapEntry {
                    key: "entries".to_string(),
                    key_source: SourceInfo::for_test(),
                    value: ConfigValue::new_array(
                        vec![yaml_toc_entry("intro", "Introduction", 1)],
                        SourceInfo::for_test(),
                    ),
                },
            ],
            SourceInfo::for_test(),
        );
        ast.meta.insert_path(&["navigation", "toc"], toc_value);

        let project = make_test_project();
        let doc = DocumentInfo::from_path("/project/doc.qmd");
        let format = Format::html();
        let binaries = BinaryDependencies::new();
        let mut ctx = RenderContext::new(&project, &doc, &format, &binaries);

        let transform = TocRenderTransform::new();
        transform.transform(&mut ast, &mut ctx).await.unwrap();

        // Should have rendered TOC
        assert!(ast.meta.contains_path(&["rendered", "navigation", "toc"]));

        // The title is stored in navigation.toc.title for the template to use
        // (the render transform doesn't include it in the HTML output)
        let toc = ast.meta.get_path(&["navigation", "toc"]).unwrap();
        let title = toc.get("title").unwrap().as_plain_text().unwrap();
        assert_eq!(title, "Quick Links");
    }
}
